ffmpegPath:     C:\bin\ffmpeg.exe

wordCloud:
  tempPath:     C:\Users\sofee\Desktop\temp\wordCloud

arcaea:
  resourcePath: C:\Users\sofee\RiderProjects\QQBOT\Marisa.Plugin.Shared\Resource\Arcaea
  tempPath:     C:\Users\sofee\Desktop\temp\arcaea
  assetsPath:   D:\arcaea_song_assets

game:
  tempPath:     C:\Users\sofee\Desktop\temp\game

osu:
  clientId:     
  clientSecret: 
  tempPath:     C:\Users\sofee\Desktop\temp\osu
  resourcePath: C:\Users\sofee\RiderProjects\QQBOT\Marisa.Plugin.Shared\Resource\Osu

chunithm:
  resourcePath: C:\Users\sofee\RiderProjects\QQBOT\Marisa.Frontend\public\assets\chunithm
  tempPath:     C:\Users\sofee\Desktop\temp\chunithm
  devToken:     
  rinNetKeyChip: 
  allNetKeyChip: 
  
ongeki:
  resourcePath: C:\Users\sofee\RiderProjects\QQBOT\Marisa.Frontend\public\assets\ongeki
  tempPath:     C:\Users\sofee\Desktop\temp\ongeki

maimai:
  secret:
    maiSalt:    
    aimeSalt:   
    aesKey:     
    aesIv:      
  resourcePath: C:\Users\sofee\RiderProjects\QQBOT\Marisa.Frontend\public\assets\maimai
  tempPath:     C:\Users\sofee\Desktop\temp\maimai
  beatMapPath:  D:\maimai_beatmap_without_bga
  version:
    maimai:
      - maimai
      - 无印
    maimai PLUS:
      - maimai plus
      - 无印plus
      - 无印加
    maimai,maimai PLUS:
      - 真
    maimai GreeN:
      - green
      - 绿
      - 超
    maimai GreeN PLUS:
      - green plus
      - 绿plus
      - 绿加
      - 檄
    maimai ORANGE:
      - orange
      - 橙
    maimai ORANGE PLUS:
      - orange plus
      - 橙plus
      - 橙加
      - 晓
    maimai PiNK:
      - pink
      - 粉
      - 桃
    maimai PiNK PLUS:
      - pink plus
      - 粉plus
      - 粉加
      - 樱
    maimai MURASAKi:
      - murasaki
      - 紫
    maimai MURASAKi PLUS:
      - murasaki plus
      - 紫plus
      - 紫加
      - 堇
    maimai MiLK:
      - milk
      - 白
      - 奶
    MiLK PLUS:
      - milk plus
      - 奶plus
      - 奶加
      - 雪
    maimai FiNALE:
      - finale
      - 辉
    "maimai,maimai PLUS,maimai GreeN,maimai GreeN PLUS,maimai ORANGE,maimai ORANGE PLUS,maimai PiNK,maimai PiNK PLUS,maimai MURASAKi,maimai MURASAKi PLUS,maimai MiLK,MiLK PLUS,maimai FiNALE":
      - 舞
    maimai でらっくす:
      - maimai deluxe
      - deluxe
      - maimai dx
      - dx
      - 熊
      - 地插
      - 华
    maimai でらっくす Splash:
      - maimai deluxe splash
      - maimai splash
      - deluxe splash
      - splash
      - maimai dx splash
      - maimai splash
      - dx splash
      - sp
      - 爽
      - 煌
    maimai でらっくす UNiVERSE:
      - universe
      - uni
      - 宙
      - 星
    maimai でらっくす FESTiVAL:
      - festival
      - fes
      - 祭

commander:
  - 642191352

randomPicture:
  imageDatabasePath:       E:\pic
  imageDatabaseKanKanPath: E:\pic\看看
  availableFileExt:
    - jpg
    - png
    - jpeg
  fileNameExclude:
    - R18
    - backup
  alias:
    赛马娘:
      - 马
    古明地恋:
      - 恋
      - 小石头
      - 古明地三鲜
      - 514
      - koishi
    雾雨魔理沙:
      - 魔理沙
      - 云里雾里沙
      - 金发孩子
      - 金可怜
      - 雨雾沙
      - 魔梨沙
      - 沙沙
      - 黑白
      - 莎莎
      - 摸你傻
    博丽灵梦:
      - 灵梦
      - 红白
      - 红白巫女
      - 无节操
      - 赤色杀人魔
      - 腋巫女
    爱丽丝·玛格特罗依德:
      - 爱丽丝
      - 小爱
      - 威震天
    帕秋莉·诺蕾姬:
      - 帕秋莉
      - 姆q
      - 帕琪
    比那名居天子:
      - 天子
      - M子
    伊吹萃香:
      - 萃香
      - 西瓜
    十六夜咲夜:
      - 咲夜
      - PAD长
    蕾米莉亚·斯卡蕾特:
      - 蕾米莉亚
      - 蕾米
      - 大小姐
      - 抱头蹲防
    芙兰朵露·斯卡蕾特:
      - 芙兰朵露
      - 芙兰
      - 二小姐
      - 二妹
    西行寺幽幽子:
      - 幽幽子
      - uuz
    魂魄妖梦:
      - 妖梦
      - 曲林静树
    东风谷早苗:
      - 早苗
      - 苗爷
    多多良小伞:
      - 小伞
    古明地觉:
      - 觉
      - satori
      - 小五
      - ⑤
    灵乌路空:
      - 阿空
      - ⑥
      - 蠢鸟
    火焰猫燐:
      - 阿燐
      - 猫车
    丰聪耳神子:
      - 神子
      - 二婶子
    圣白莲:
      - 莲妈
    秦心:
      - 心
    二岩猯藏:
      - 大狸子
    少名针妙丸:
      - 针妙丸
      - 小碗
    封兽鵺:
      - 鵺
    村纱水蜜:
      - 船长
    鬼人正邪:
      - 正邪
      - 政协
      - 邪正人鬼
    红美铃:
      - 红师傅
      - 美铃
      - 中国
    哆来咪·苏伊特:
      - 哆来咪
      - 123
    爱塔妮缇·拉尔瓦:
      - 拉尔瓦
      - 大扑棱蛾子
    八坂神奈子:
      - 神奈子
      - 神妈
    洩矢诹访子:
      - 诹访子
      - 青蛙子
    射命丸文:
      - 文文
      - 香港记者
    河城荷取:
      - 河童
    赫卡提亚·拉碧斯拉祖利:
      - 赫卡提亚
      - 赫卡
      - 五球女神
    茨木华扇:
      - 华扇
      - 包子仙人
    摩多罗隐岐奈:
      - 摩多罗
    八意永琳:
      - 永琳
      - 师匠
    蓬莱山辉夜:
      - neet姬
      - 辉夜
      - 辉夜姬
    铃仙·优昙华院·因幡:
      - 铃仙
      - 受兔
      - 铃仙·U·因幡
      - 铃仙·优昙华院·稻叶
    永江衣玖:
      - 衣玖
      - 19
      - 皇带鱼
    宇佐见堇子:
      - 堇子
    寅丸星:
      - 大师兄
      - 老虎
    娜兹玲:
      - 纳兹玲
      - 娜兹琳
      - 老鼠
      - 最强一面
    克劳恩皮丝:
      - 皮丝
      - 美国妖精
      - 过膝袜
    露米娅:
      - ⑩
    琪露诺:
      - ⑨
    藤原妹红:
      - 妹红
    上白泽慧音:
      - 慧音
      - 老师
    稗田阿求:
      - 阿求
    本居小铃:
      - 小铃
      - 防撞桶
    八云蓝:
      - 蓝
      - 蓝妈
    八云紫:
      - 紫
      - 紫妈
      - 紫妹
    橙:
      - 橙喵
    冈崎梦美:
      - 草莓
      - 教授
    赤蛮奇:
      - ⑦
    坂田合欢乃:
      - 坂田合欢
      - 欢姐
    姬海棠果:
      - 果果
    犬走椛:
      - 椛椛
    物部布都:
      - 布嘟嘟
    稀神探女:
      - 探女
      - 黄旭东
    小野塚小町:
      - 乳町
      - 小町
    四季映姬·亚玛萨那度:
      - 四季映姬
      - 四季大人
    因幡帝:
      - 因幡天为
      - 帝帝
      - 小老帝
      - 腹黑兔
    水桥帕露西:
      - 桥姬
      - 帕露西
    依神紫苑:
      - 藤原妹蓝
    莉莉白:
      - 莉莉霍瓦特
    霍青娥:
      - 青娥娘娘
      - 娘娘
    米斯蒂娅·萝蕾拉:
      - 米斯蒂娅
      - 小碎骨
      - 老板娘
    幽谷响子:
      - 复读机
    梅蒂欣·梅兰可莉:
      - 梅蒂欣
      - 毒人偶
    风见幽香:
      - 幽香
      - 花妈
    大妖精:
      - 大酱
    陈睿:
      - cr
      - uncle
      - 叔叔
    初音未来:
      - miku
      - 39
    原神:
      - o
      - 原

fortune:
  # 朝向
  direction:
    - 东
    - 南
    - 西
    - 北
    - 东南
    - 西南
    - 东北
    - 西北
  # 机位
  position:
    - P1
    - P2
    - P1
    - P2
    - P1
    - P2
    - P1
    - P2
    - P1
    - P2
    - 维修位
  rhythmGames:
    - Arcaea
    - BanG Dream! 少女乐团派对!
    - Beat Saber
    - Beatmania IIDX
    - CHUNITHM
    - Cytus II
    - D4DJ Groovy Mix
    - DJMAX
    - Dance Dance Revolution
    - Deemo
    - Dynamix
    - GROOVE COASTER
    - Guitar Hero
    - Lanota
    - Love Live
    - Malody
    - Mush Dash
    - O.N.G.E.K.I.
    - Orzmic
    - OverRapid
    - Phigros
    - Project DIVA Future Tone
    - Project Sekai (プロセカ)
    - SOUND VOLTEX
    - VOEZ
    - WACCA
    - jubeat
    - maimaiDX
    - osu!
    - デレステ
    - 不可思议乐队
    - 东方弹幕神乐
    - 冰与火之舞
    - 吉他英雄
    - 同步音律喵赛克
    - 命运歌姬
    - 太鼓达人
    - 节奏大师
    - 节奏海拉鲁
    - 阳春白雪
    - 音击
    - 音灵
    - 网易云音乐
  events:
    - event: 收歌
      positive:
        - 又有资本可以炫耀了。
        - 排行榜第一就在下一次！
        - 攻克卡住多时的难点。
        - 手感爆棚，曲曲理论值。
      negative:
        - 快要收歌的时候会来一通无关紧要的电话。
        - 会在最后关头卡帧掉 note。
        - 延迟漂移个个 Good，曲曲延迟各不同。
        - 看见这个 note 了吗？你 接 不 住。
    - event: 炫耀成绩
      positive:
        - 获得万众敬仰，收割万人膝盖。
        - 一曲成名，万人膜拜。
        - 本群都是你的小弟啦！
      negative:
        - 警察叔叔，对，就是这个杀人犯。
        - 容易被群友拉黑或报复。
    - event: 复读
      positive:
        - 有时候，人云亦云也是一种生存方式。
      negative:
        - 你的对手是鸽子。
    - event: 爆肝
      positive:
        - 说不定下一盘就创纪录了呢。
        - 大力出奇迹。
        - 努力使人进步，肝爆让人快乐。
        - 限时梯子爬完了吗？
      negative:
        - 会因为腱鞘炎而进医院。
        - 屏幕会碎掉的。
        - 醒醒，限时活动没了。
    - event: 课金
      positive:
        - 早买早享受，晚买哭着求。
        - 看到这个新曲子了吗？我有了！
      negative:
        - 第二天就 50% off。
        - 银行卡余额不足，支付失败。
        - 接下来的一个月只能吃土。
    - event: 出勤
      positive:
        - 有机会与大佬切磋交流，获得音游经验值双倍加成。
        - 今日的机厅无人打扰，获得霸机机会。
        - 会忽然成为机厅中的焦点人物。
      negative:
        - 会不小心把机器拍坏。
        - 今天商场停电的概率比较高。
        - 音游街机前全是众众众众众众众众。
        - 会被大佬碾压。
    - event: 卖弱
      positive:
        - 楚楚动人更容易打动群友。
      negative:
        - Boy♂︎next♂︎door。
    - event: 唱脑力
      positive:
        - 唱一次提升醒脑，唱两次精神百倍。
      negative:
        - 会与复读机一起，对群聊造成不可逆的毁灭打击。
    - event: 刷剧情
      positive:
        - 会度过充实的一天。
      negative:
        - 会被虐到。
    - event: 爬梯子
      positive:
        - 今天就可以到顶哦。
      negative:
        - 会不小心把所有碎片全用来爬梯子。
    - event: 看手元
      positive:
        - 从手元中获得一点音游经验。
      negative:
        - 会被大佬闪瞎。
    - event: 录手元
      positive:
        - 音游届的未来新星 up 主就是你。
      negative:
        - 打完歌才发现忘记开录像。
    - event: 开浴霸
      positive:
        - 不如跳舞，玩音游不如跳舞。
      negative:
        - 会把家/宿舍点着的。
    - event: 研究魔王曲谱面
      positive:
        - 发现收歌的秘诀。
      negative:
        - 你个凡人还想收魔王？Naive！
    - event: 挑战魔王曲
      positive:
        - 一上来就是一个新纪录。
      negative:
        - 有这点时间还不如干点别的。
    - event: 咕咕咕
      positive:
        - 一时咕一时爽。
      negative:
        - 会被抓起来，被群友唾沫淹死。
    - event: 与群友水聊
      positive:
        - 扶我起来我还能打字。
      negative:
        - 一不小心就被大佬闪瞎。
    - event: 考段
      positive:
        - 底力飞升，什么都能糊过去，考段稳过。
      negative:
        - 眼花缭乱，各种看不清，怎么考都会在最后crash。
    - event: 吃萨利亚
      positive:
        - 毕竟是音游狗餐厅。
      negative:
        - 真的不选对面那个吉野家吗？
    - event: 打课题
      positive:
        - 突然就获得最高积分。
      negative:
        - 别人成绩都比你高，于是自闭。
    - event: 面基
      positive:
        - 两个大佬一起，给魔王曲带来意想不到的灾难。
      negative:
        - 会连烤全鸽都吃不到。
    - event: 制谱
      positive:
        - 文思泉涌、脑洞大开，一不小心制作出十分优良的谱面。
      negative:
        - 绞尽脑汁却想不出做出什么谱面，只能加入钟国谱面大军。
    - event: 吃葡萄
      positive:
        - 音游狗水果，好吃的水果。
      negative:
        - 白内障看不清，杀铺 Ice 滴眼睛。
    - event: 催更
      positive:
        - 明天音游厂家就更新。
      negative:
        - 就知道催，老谱没收催什么催？
    - event: 迫害大佬
      positive:
        - 迫害是大佬进步的阶梯。
        - 迫害语录 +1。
      negative:
        - 亲爱的，你号没了。
        - 管理清一下？
        - 喝茶警告。
    - event: 唱打
      positive:
        - 大家快看，这个唱歌好听的小哥哥（小姐姐）手速怎么这么快？
        - 唱歌又好听，手速又超快，超喜欢在里面 der。
      negative:
        - 唱，跳，rap，再来个篮球，你就是音游区最蔡的仔。
    - event: 算命
      positive:
        - 不遵守你的 IM 帐户待会就被封。
        - 算啥都准。
      negative:
        - 魔理沙因为算太多刷屏被群管理封号。
        - 诸事不宜。
    - event: 挑战单手过关
      positive:
        - 一只更比两只强。
      negative:
        - 不需要的手可以捐给有需要的人。
